name: Rust

env:
  CARGO_TERM_COLOR: always

on:
  push:
    branches: [ "main", "master", "prod" ]
    tags: [ "v*.*.*" ]
  schedule:
    - cron: "30 9 * * 5"
  workflow_dispatch:
    inputs:
      publish:
        default: true
        description: 'Publish'
        required: true
        type: boolean

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - wasm32-unknown-unknown
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        run: |
          rustup default nightly
          rustup target add ${{ matrix.target }} --toolchain nightly
      - run: cargo build --release -v --workspace --target ${{ matrix.target }}
      - run: cargo test --all --all-features --release -v --workspace --target ${{ matrix.target }}
  publish:
    if: ${{ github.event.inputs.publish }}
    name: Publish
    runs-on: ubuntu-latest
    strategy:
      matrix:
        crate:
          - template-rs-worker
    steps:
      - uses: actions/checkout@v3
      - name: Publish (${{matrix.crat}})
        run: cargo publish --all-features --crate ${{ matrix.crate }} --verbose --token ${{ secrets.CARGO_REGISTRY_TOKEN }}